### ISSUE TITLE
Lua Language Server Notation

### ISSUE THREAD

**Issue by YvanCywan** [DreamWeave-MP/CoreScripts#15]
Lua Language Server Notation should very much be utilised in CoreScripts.

https://github.com/LuaLS/lua-language-server/wiki/Annotations

This provides automatic support for intellisense on VSCode (I'm pretty sure some other IDEs/editors that support Lua Language Server) and can be used to to provide additional context for reading files.

Example:
```lua
---@param seconds number
---@return boolean isWithinTime
local function isOnTime(seconds)
    return seconds < 5
end
```

**Comment by YvanCywan** [comment]
Hi all,

I've added everyone to this one because I think it'll be a good idea if we all go through core scripts and take like a few files and annotate them properly. I know it's a bit boring, but this works with intellisense, and this would drastically reduce the barrier of entry for new developers. Along with improving debug-ability of the code as we have clearly documented types.

**Comment by magicaldave** [comment]
When creation annotations, please name your branch `doc/annotations-FILENAME` and request a pull into `doc/annotations`. When we've finished, we'll merge the whole bitch into master.

Tracking for completion and assignments per-file. Check them off and please leave a comment if you self-assign one.

scripts/:
- [x] animHelper.lua - Dave (complete) #32 
- [x] clientVariableScopes.lua - Dave (awaiting review) #33 
- [x] color.lua - Dave (awaiting review) #35
- [ ] commandHandler.lua
- [ ] config.lua
- [ ] contentFixer.lua
- [ ] customCommandHooks.lua
- [ ] customEventHooks.lua
- [ ] customScripts.lua
- [ ] database.lua
- [ ] dataTableBuilder.lua
- [ ] defaultCommands.lua
- [ ] enumerations.lua
- [ ] eventHandler.lua
- [ ] guiHelper.lua
- [ ] inventoryHelper.lua
- [ ] logicHandler.lua
- [ ] menuHelper.lua
- [ ] packetBuilder.lua
- [ ] packetReader.lua
- [ ] serverCore.lua
- [ ] speechCollections.lua
- [ ] speechHelper.lua
- [ ] stateHelper.lua
- [ ] vectors.lua
- [x] wrapper.lua - Dave - #37 - Done

scripts/cell:
- [ ] base.lua
- [ ] json.lua
- [ ] sql.lua

scripts/player:
- [ ] base.lua
- [ ] json.lua
- [ ] sql.lua

scripts/menu:
- [ ] advancedExample.lua
- [ ] defaultCrafting.lua
- [ ] help.lua

scripts/recordstore:
- [ ] base.lua
- [ ] json.lua
- [ ] sql.lua

scripts/world:
- [ ] base.lua
- [ ] json.lua
- [ ] sql.lua

lib/lua:
- [ ] classy.lua
- [ ] dkjson.lua
- [ ] fileHelper.lua
- [ ] irc.lua
- [ ] jsonInterface.lua
- [ ] lanes.lua
- [ ] ltn12-lanes.lua
- [ ] ltn12.lua
- [ ] mime-lanes.lua
- [ ] patterns.lua
- [ ] socket-lanes.lua
- [ ] tableHelper.lua
- [ ] time.lua
- [ ] utils.lua
